BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE USUARIOS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USUARIOS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/
CREATE TABLE USUARIOS (
    id_usuario NUMBER PRIMARY KEY,
    nome VARCHAR2(150) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    senha_hash VARCHAR2(255) NOT NULL,
    token_notificacao_push VARCHAR2(255) NULL,
    data_criacao TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE SEQUENCE SEQ_USUARIOS START WITH 1 INCREMENT BY 1 NOCACHE;
COMMIT;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE HOTSPOTS_EVENTOS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HOTSPOTS_EVENTOS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/
CREATE TABLE HOTSPOTS_EVENTOS (
    id_hotspot NUMBER PRIMARY KEY,
    centroide_latitude NUMBER(10, 7) NOT NULL,
    centroide_longitude NUMBER(10, 7) NOT NULL,
    raio_estimado_km NUMBER(6, 2) NULL,
    poligono_geojson CLOB NULL,
    numero_alertas_agrupados NUMBER DEFAULT 0 NOT NULL,
    severidade_predominante VARCHAR2(20) NOT NULL
        CHECK (severidade_predominante IN ('BAIXA', 'MEDIA', 'ALTA', 'CRITICA')),
    tipo_predominante VARCHAR2(30) NOT NULL
        CHECK (tipo_predominante IN ('ALAGAMENTO', 'RISCO_DESLIZAMENTO', 'DESLIZAMENTO_OCORRIDO', 'OUTRO_PERIGO', 'MISTO')),
    resumo_publico VARCHAR2(500) NULL,
    timestamp_criacao TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    timestamp_ultima_atividade TIMESTAMP WITH TIME ZONE NOT NULL,
    status_hotspot VARCHAR2(20) NOT NULL
        CHECK (status_hotspot IN ('ATIVO', 'OBSOLETO'))
);
CREATE SEQUENCE SEQ_HOTSPOTS_EVENTOS START WITH 1 INCREMENT BY 1 NOCACHE;
COMMIT;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ALERTAS_USUARIO CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ALERTAS_USUARIO';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/
CREATE TABLE ALERTAS_USUARIO (
    id_alerta NUMBER PRIMARY KEY,
    id_usuario_reportou NUMBER NOT NULL,
    descricao_texto VARCHAR2(2000) NOT NULL,
    latitude NUMBER(10, 7) NOT NULL,
    longitude NUMBER(10, 7) NOT NULL,
    timestamp_reporte TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status_alerta VARCHAR2(30) NOT NULL
        CHECK (status_alerta IN ('PENDENTE_IA', 'CLASSIFICADO_IA', 'PROCESSADO_CLUSTER', 'PROCESSADO_CLUSTER_RUIDO', 'PROCESSADO_CLUSTER_SEM_HOTSPOT', 'EXPIRADO')),
    severidade_ia VARCHAR2(20) NULL
        CHECK (severidade_ia IS NULL OR severidade_ia IN ('BAIXA', 'MEDIA', 'ALTA', 'CRITICA')),
    tipo_ia VARCHAR2(30) NULL
        CHECK (tipo_ia IS NULL OR tipo_ia IN ('ALAGAMENTO', 'RISCO_DESLIZAMENTO', 'DESLIZAMENTO_OCORRIDO', 'OUTRO_PERIGO')),
    id_hotspot_associado NUMBER NULL,
    CONSTRAINT fk_alertas_usuario_ref_usuarios FOREIGN KEY (id_usuario_reportou) REFERENCES USUARIOS (id_usuario),
    CONSTRAINT fk_alertas_hotspot_ref_hotspots FOREIGN KEY (id_hotspot_associado) REFERENCES HOTSPOTS_EVENTOS (id_hotspot)
);
CREATE SEQUENCE SEQ_ALERTAS_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE;
COMMIT;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE LOCAIS_MONITORADOS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_LOCAIS_MONITORADOS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/
CREATE TABLE LOCAIS_MONITORADOS (
    id_local_monitorado NUMBER PRIMARY KEY,
    id_usuario_registrou NUMBER NOT NULL,
    nome_local VARCHAR2(100) NOT NULL,
    latitude NUMBER(10, 7) NOT NULL,
    longitude NUMBER(10, 7) NOT NULL,
    raio_notificacao_km NUMBER(5, 2) NOT NULL,
    data_criacao TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
    CONSTRAINT fk_locais_monitorados_usuario_ref_usuarios FOREIGN KEY (id_usuario_registrou) REFERENCES USUARIOS (id_usuario),
);
CREATE SEQUENCE SEQ_LOCAIS_MONITORADOS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_LOCAIS_MONITORADOS_USER_ID ON LOCAIS_MONITORADOS (user_id);
COMMIT;

EXIT;